version: '2'

services:
    els:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
        restart: always
        container_name: els
        hostname: els
        networks:
        - elastic-jaeger
        environment:
          - bootstrap.memory_lock=true
          - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ports:
          - "9200:9200"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        mem_limit: 1g
        volumes:
          - esdata1:/usr/share/elasticsearch/data
          - eslog:/usr/share/elasticsearch/logs
          - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      command: [ "--span-storage.type=elasticsearch", "--es.server-urls=http://els:9200", "--collector.zipkin.http-port=9411"]
      ports:
        - "14269"
        - "14268:14268"
        - "14267:14267"
        - "14250"
        - "9411:9411"
      container_name: jaeger-collector
      hostname: jaeger-collector
      restart: unless-stopped
      networks:
      - elastic-jaeger
      depends_on:
        - els

    jaeger-query:
      image: jaegertracing/jaeger-query
      command: ["--span-storage.type=elasticsearch", "--es.server-urls=http://els:9200", "--es.sniffer=false", "--log-level=debug"]
      ports:
        - "16686:16686"
        - "16687"
      restart: unless-stopped
      container_name: jaeger-query
      hostname: jaeger-query
      networks:
        - elastic-jaeger
      depends_on:
        - els
        - jaeger-collector

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      networks:
        - elastic-jaeger
      depends_on:
        - els
        - jaeger-collector
      restart: unless-stopped
      container_name: jaeger-agent
      hostname: jaeger-agent

volumes:
  esdata1:
    driver: local
  eslog:
    driver: local
networks:
  elastic-jaeger:
    driver: bridge